### ISSUE TITLE
TypeError: null is not an object (evaluating '_reactNative.NativeModules.ReactNativePickerModule.show')

### ISSUE THREAD

**Issue by flora8984461** [talut/react-native-picker-module#46]
Seems this error happens on expo android.
I am on expo sdk-41.0.0 ("react-native": "https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz")
react: 16.13.1

```
TypeError: null is not an object (evaluating '_reactNative.NativeModules.ReactNativePickerModule.show')
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
at [native code]:null in flushedQueue
at [native code]:null in invokeCallbackAndReturnFlushedQueue
```

It's working if I ejected from expo.

**Comment by flora8984461** [comment]
I am going to check https://github.com/talut/react-native-picker-module/issues/6
